[2025-06-30T15:08:13.962+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_card_etl.etl_cards_task manual__2025-06-30T15:08:12.214223+00:00 [queued]>
[2025-06-30T15:08:13.975+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_card_etl.etl_cards_task manual__2025-06-30T15:08:12.214223+00:00 [queued]>
[2025-06-30T15:08:13.976+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-30T15:08:13.994+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-30 15:08:12.214223+00:00
[2025-06-30T15:08:14.001+0000] {standard_task_runner.py:60} INFO - Started process 14434 to run task
[2025-06-30T15:08:14.005+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_card_etl', 'etl_cards_task', 'manual__2025-06-30T15:08:12.214223+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/etl_dim_card_dag.py', '--cfg-path', '/tmp/tmpbc0ltxbr']
[2025-06-30T15:08:14.008+0000] {standard_task_runner.py:88} INFO - Job 104: Subtask etl_cards_task
[2025-06-30T15:08:14.089+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_card_etl.etl_cards_task manual__2025-06-30T15:08:12.214223+00:00 [running]> on host 65da94c758f2
[2025-06-30T15:08:14.394+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='dim_card_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T15:08:12.214223+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T15:08:12.214223+00:00'
[2025-06-30T15:08:14.396+0000] {etl_dim_card_dag.py:23} INFO - Starting ETL for cards
[2025-06-30T15:08:14.433+0000] {extract_data.py:25} INFO - ✅ Extracted CARDS_data.csv with 6146 records
[2025-06-30T15:08:14.434+0000] {transform_dim_card.py:23} INFO - Starting transformation of CARDS data.
[2025-06-30T15:08:14.459+0000] {transform_dim_card.py:45} INFO - ✅finished transformation of CARDS data.
[2025-06-30T15:08:14.464+0000] {load_data.py:34} INFO - Successfully created database connection engine.
[2025-06-30T15:08:14.595+0000] {load_data.py:94} ERROR - ❌Error loading data into table 'dim_card': (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")
[SQL: SELECT TOP 1 1 FROM financial.dim_card]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-06-30T15:08:14.596+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_dim_card_dag.py", line 27, in my_etl_task
    load.load_dataframe_to_sql(cards_df_clean,'dim_card',engine,'financial')
  File "/opt/airflow/ETL/load_data.py", line 75, in load_dataframe_to_sql
    result = conn.execute(f"SELECT TOP 1 1 FROM {schema}.{table_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    return self._exec_driver_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1674, in _exec_driver_sql
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")
[SQL: SELECT TOP 1 1 FROM financial.dim_card]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-06-30T15:08:14.627+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dim_card_etl, task_id=etl_cards_task, execution_date=20250630T150812, start_date=20250630T150813, end_date=20250630T150814
[2025-06-30T15:08:14.649+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task etl_cards_task ((pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")
[SQL: SELECT TOP 1 1 FROM financial.dim_card]
(Background on this error at: https://sqlalche.me/e/14/f405); 14434)
[2025-06-30T15:08:14.703+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-30T15:08:14.726+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
