[2025-06-25T11:41:00.505+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-25T11:40:58.827481+00:00 [queued]>
[2025-06-25T11:41:00.517+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-25T11:40:58.827481+00:00 [queued]>
[2025-06-25T11:41:00.519+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-25T11:41:00.538+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-25 11:40:58.827481+00:00
[2025-06-25T11:41:00.545+0000] {standard_task_runner.py:60} INFO - Started process 1042 to run task
[2025-06-25T11:41:00.550+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cards_etl', 'etl_cards_task', 'manual__2025-06-25T11:40:58.827481+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/etl_cards_dag.py', '--cfg-path', '/tmp/tmp91667wbs']
[2025-06-25T11:41:00.553+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask etl_cards_task
[2025-06-25T11:41:00.625+0000] {task_command.py:423} INFO - Running <TaskInstance: cards_etl.etl_cards_task manual__2025-06-25T11:40:58.827481+00:00 [running]> on host 65da94c758f2
[2025-06-25T11:41:01.040+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='cards_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T11:40:58.827481+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T11:40:58.827481+00:00'
[2025-06-25T11:41:01.042+0000] {etl_cards_dag.py:21} INFO - Starting ETL for cards
[2025-06-25T11:41:01.081+0000] {extract_data.py:22} INFO - âœ… Extracted cards_data.csv with 6146 records
[2025-06-25T11:41:01.086+0000] {transform_cards.py:71} INFO - Removed columns ['client_id', 'card_number', 'cvv'] from CARDS data.
[2025-06-25T11:41:01.102+0000] {warnings.py:109} WARNING - /opt/***/ETL/transform_cards.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['expires'] = pd.to_datetime(df['expires'], errors='coerce')

[2025-06-25T11:41:01.105+0000] {transform_cards.py:89} INFO - Set data types for CARDS data.
[2025-06-25T11:41:01.110+0000] {load_data.py:34} INFO - Successfully created database connection engine.
[2025-06-25T11:41:14.238+0000] {load_data.py:81} INFO - Successfully loaded data into table 'financial.dim_card'. 6146 rows and 10 columns
[2025-06-25T11:41:14.239+0000] {etl_cards_dag.py:27} INFO - Finished ETL for cards
[2025-06-25T11:41:14.239+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-25T11:41:14.252+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cards_etl, task_id=etl_cards_task, execution_date=20250625T114058, start_date=20250625T114100, end_date=20250625T114114
[2025-06-25T11:41:14.300+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-25T11:41:14.602+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
