[2025-06-19T12:14:03.928+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-19T12:13:34.568801+00:00 [queued]>
[2025-06-19T12:14:03.955+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-19T12:13:34.568801+00:00 [queued]>
[2025-06-19T12:14:03.956+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-19T12:14:03.997+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-19 12:13:34.568801+00:00
[2025-06-19T12:14:04.015+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2025-06-19T12:14:04.024+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cards_etl', 'etl_cards_task', 'manual__2025-06-19T12:13:34.568801+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_cards_dag.py', '--cfg-path', '/tmp/tmp5odup32q']
[2025-06-19T12:14:04.031+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask etl_cards_task
[2025-06-19T12:14:04.208+0000] {task_command.py:423} INFO - Running <TaskInstance: cards_etl.etl_cards_task manual__2025-06-19T12:13:34.568801+00:00 [running]> on host 9aab1b97046e
[2025-06-19T12:14:05.257+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='cards_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T12:13:34.568801+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T12:13:34.568801+00:00'
[2025-06-19T12:14:05.261+0000] {etl_cards_dag.py:21} INFO - Starting ETL for cards
[2025-06-19T12:14:05.349+0000] {extract_data.py:22} INFO - âœ… Extracted cards_data.csv with 6146 records
[2025-06-19T12:14:05.351+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_cards_dag.py", line 23, in my_etl_task
    cards_df_clean1 = extract.cards_remove_rename_columns(cards_df)
AttributeError: module 'ETL.extract_data' has no attribute 'cards_remove_rename_columns'
[2025-06-19T12:14:05.386+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cards_etl, task_id=etl_cards_task, execution_date=20250619T121334, start_date=20250619T121403, end_date=20250619T121405
[2025-06-19T12:14:05.414+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task etl_cards_task (module 'ETL.extract_data' has no attribute 'cards_remove_rename_columns'; 177)
[2025-06-19T12:14:05.491+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-19T12:14:05.535+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
