[2025-06-19T11:55:08.494+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-19T11:54:41.227711+00:00 [queued]>
[2025-06-19T11:55:08.514+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-19T11:54:41.227711+00:00 [queued]>
[2025-06-19T11:55:08.516+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-19T11:55:08.548+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-19 11:54:41.227711+00:00
[2025-06-19T11:55:08.562+0000] {standard_task_runner.py:60} INFO - Started process 939 to run task
[2025-06-19T11:55:08.568+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cards_etl', 'etl_cards_task', 'manual__2025-06-19T11:54:41.227711+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_cards_dag.py', '--cfg-path', '/tmp/tmppmnvr6ka']
[2025-06-19T11:55:08.573+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask etl_cards_task
[2025-06-19T11:55:08.684+0000] {task_command.py:423} INFO - Running <TaskInstance: cards_etl.etl_cards_task manual__2025-06-19T11:54:41.227711+00:00 [running]> on host 7d32beed4a77
[2025-06-19T11:55:09.245+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='cards_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T11:54:41.227711+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T11:54:41.227711+00:00'
[2025-06-19T11:55:09.250+0000] {etl_cards_dag.py:21} INFO - Starting ETL for cards
[2025-06-19T11:55:09.259+0000] {extract_data.py:25} ERROR - ‚ùå Error loading cards_data.csv: [Errno 2] No such file or directory: 'C:\\Users\\jimmy\\Documents\\Data Projects\\Project\\Financial Transactions Project\\data/cards_data.csv'
[2025-06-19T11:55:09.262+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_cards_dag.py", line 22, in my_etl_task
    cards_df = extract.extract_cards_data()
  File "/opt/airflow/ETL/extract_data.py", line 21, in extract_cards_data
    df = pd.read_csv(config.CARDS_FILE)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jimmy\\Documents\\Data Projects\\Project\\Financial Transactions Project\\data/cards_data.csv'
[2025-06-19T11:55:09.305+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cards_etl, task_id=etl_cards_task, execution_date=20250619T115441, start_date=20250619T115508, end_date=20250619T115509
[2025-06-19T11:55:09.339+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task etl_cards_task ([Errno 2] No such file or directory: 'C:\\Users\\jimmy\\Documents\\Data Projects\\Project\\Financial Transactions Project\\data/cards_data.csv'; 939)
[2025-06-19T11:55:09.385+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-19T11:55:09.420+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
