[2025-06-30T13:42:29.040+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_card_etl.etl_cards_task manual__2025-06-30T13:41:57.324813+00:00 [queued]>
[2025-06-30T13:42:29.067+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_card_etl.etl_cards_task manual__2025-06-30T13:41:57.324813+00:00 [queued]>
[2025-06-30T13:42:29.069+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-30T13:42:29.108+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-30 13:41:57.324813+00:00
[2025-06-30T13:42:29.130+0000] {standard_task_runner.py:60} INFO - Started process 13555 to run task
[2025-06-30T13:42:29.138+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_card_etl', 'etl_cards_task', 'manual__2025-06-30T13:41:57.324813+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/etl_dim_card_dag.py', '--cfg-path', '/tmp/tmpqncl8ddx']
[2025-06-30T13:42:29.144+0000] {standard_task_runner.py:88} INFO - Job 94: Subtask etl_cards_task
[2025-06-30T13:42:29.266+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_card_etl.etl_cards_task manual__2025-06-30T13:41:57.324813+00:00 [running]> on host 65da94c758f2
[2025-06-30T13:42:30.138+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='dim_card_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T13:41:57.324813+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T13:41:57.324813+00:00'
[2025-06-30T13:42:30.141+0000] {etl_dim_card_dag.py:23} INFO - Starting ETL for cards
[2025-06-30T13:42:30.218+0000] {extract_data.py:25} INFO - ✅ Extracted CARDS_data.csv with 6146 records
[2025-06-30T13:42:30.219+0000] {transform_dim_card.py:23} INFO - Starting transformation of CARDS data.
[2025-06-30T13:42:30.297+0000] {transform_dim_card.py:45} INFO - ✅finished transformation of CARDS data.
[2025-06-30T13:42:30.309+0000] {load_data.py:34} INFO - Successfully created database connection engine.
[2025-06-30T13:42:30.609+0000] {load_data.py:95} ERROR - ❌Error loading data into table 'dim_card': (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")
[SQL: SELECT COUNT(*) FROM financial.dim_card]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-06-30T13:42:30.611+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_dim_card_dag.py", line 27, in my_etl_task
    load.load_dataframe_to_sql(cards_df_clean,'dim_card',engine,'financial')
  File "/opt/airflow/ETL/load_data.py", line 75, in load_dataframe_to_sql
    result = conn.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    return self._exec_driver_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1674, in _exec_driver_sql
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")
[SQL: SELECT COUNT(*) FROM financial.dim_card]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-06-30T13:42:30.658+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_card_etl, task_id=etl_cards_task, execution_date=20250630T134157, start_date=20250630T134229, end_date=20250630T134230
[2025-06-30T13:42:30.693+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 94 for task etl_cards_task ((pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'financial.dim_card'. (208) (SQLExecDirectW)")
[SQL: SELECT COUNT(*) FROM financial.dim_card]
(Background on this error at: https://sqlalche.me/e/14/f405); 13555)
[2025-06-30T13:42:30.762+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-30T13:42:30.807+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
